#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Genera medias.json y medias.csv con los 150 jugadores: nombre, equipo,
media (OVR) NBA 2K26, posicion, rareza y ruta de la foto.
Medias de estrellas = Top 100 oficial 2K26. Roleros = mejor valor actual recopilado."""
import os, json, csv

BASE = os.path.dirname(os.path.abspath(__file__))
FOTOS = os.path.join(BASE, "fotos-nba")

# slug -> (Nombre, OVR, posicion)
DATA = {
    # 01 Oklahoma City Thunder
    "shai-gilgeous-alexander": ("Shai Gilgeous-Alexander", 98, "PG"),
    "jalen-williams": ("Jalen Williams", 90, "SF"),
    "chet-holmgren": ("Chet Holmgren", 88, "C"),
    "isaiah-hartenstein": ("Isaiah Hartenstein", 82, "C"),
    "luguentz-dort": ("Luguentz Dort", 81, "SG"),
    # 02 New York Knicks
    "jalen-brunson": ("Jalen Brunson", 93, "PG"),
    "karl-anthony-towns": ("Karl-Anthony Towns", 92, "C"),
    "og-anunoby": ("OG Anunoby", 85, "SF"),
    "mikal-bridges": ("Mikal Bridges", 84, "SF"),
    "mitchell-robinson": ("Mitchell Robinson", 80, "C"),
    # 03 Denver Nuggets
    "nikola-jokic": ("Nikola Jokic", 98, "C"),
    "jamal-murray": ("Jamal Murray", 86, "PG"),
    "cameron-johnson": ("Cameron Johnson", 83, "SF"),
    "aaron-gordon": ("Aaron Gordon", 82, "PF"),
    "christian-braun": ("Christian Braun", 80, "SG"),
    # 04 Orlando Magic
    "paolo-banchero": ("Paolo Banchero", 89, "PF"),
    "franz-wagner": ("Franz Wagner", 86, "SF"),
    "desmond-bane": ("Desmond Bane", 83, "SG"),
    "jalen-suggs": ("Jalen Suggs", 82, "SG"),
    "wendell-carter-jr": ("Wendell Carter Jr.", 80, "C"),
    # 05 Houston Rockets
    "kevin-durant": ("Kevin Durant", 93, "SF"),
    "alperen-sengun": ("Alperen Sengun", 87, "C"),
    "amen-thompson": ("Amen Thompson", 87, "PG"),
    "jabari-smith-jr": ("Jabari Smith Jr.", 80, "PF"),
    "dorian-finney-smith": ("Dorian Finney-Smith", 75, "SF"),
    # 06 Minnesota Timberwolves
    "anthony-edwards": ("Anthony Edwards", 95, "SG"),
    "julius-randle": ("Julius Randle", 86, "PF"),
    "rudy-gobert": ("Rudy Gobert", 84, "C"),
    "jaden-mcdaniels": ("Jaden McDaniels", 82, "PF"),
    "mike-conley": ("Mike Conley", 77, "PG"),
    # 07 LA Clippers
    "kawhi-leonard": ("Kawhi Leonard", 92, "SF"),
    "james-harden": ("James Harden", 89, "PG"),
    "ivica-zubac": ("Ivica Zubac", 87, "C"),
    "john-collins": ("John Collins", 82, "PF"),
    "bradley-beal": ("Bradley Beal", 77, "SG"),
    # 08 Golden State Warriors
    "stephen-curry": ("Stephen Curry", 94, "PG"),
    "jimmy-butler": ("Jimmy Butler", 87, "SF"),
    "draymond-green": ("Draymond Green", 81, "PF"),
    "brandin-podziemski": ("Brandin Podziemski", 78, "SG"),
    "al-horford": ("Al Horford", 77, "C"),
    # 09 Atlanta Hawks
    "trae-young": ("Trae Young", 90, "PG"),
    "dyson-daniels": ("Dyson Daniels", 83, "SG"),
    "jalen-johnson": ("Jalen Johnson", 81, "PF"),
    "onyeka-okongwu": ("Onyeka Okongwu", 81, "C"),
    "zaccharie-risacher": ("Zaccharie Risacher", 77, "SF"),
    # 10 Los Angeles Lakers
    "luka-doncic": ("Luka Doncic", 95, "PG"),
    "lebron-james": ("LeBron James", 94, "SF"),
    "austin-reaves": ("Austin Reaves", 85, "SG"),
    "rui-hachimura": ("Rui Hachimura", 81, "PF"),
    "deandre-ayton": ("Deandre Ayton", 79, "C"),
    # 11 Dallas Mavericks
    "anthony-davis": ("Anthony Davis", 93, "PF"),
    "cooper-flagg": ("Cooper Flagg", 82, "SF"),
    "daniel-gafford": ("Daniel Gafford", 80, "C"),
    "klay-thompson": ("Klay Thompson", 79, "SG"),
    "dangelo-russell": ("D'Angelo Russell", 76, "PG"),
    # 12 San Antonio Spurs
    "victor-wembanyama": ("Victor Wembanyama", 97, "C"),
    "deaaron-fox": ("De'Aaron Fox", 85, "PG"),
    "devin-vassell": ("Devin Vassell", 82, "SG"),
    "stephon-castle": ("Stephon Castle", 82, "SG"),
    "harrison-barnes": ("Harrison Barnes", 77, "SF"),
    # 13 Cleveland Cavaliers
    "donovan-mitchell": ("Donovan Mitchell", 93, "SG"),
    "evan-mobley": ("Evan Mobley", 89, "PF"),
    "jarrett-allen": ("Jarrett Allen", 84, "C"),
    "deandre-hunter": ("De'Andre Hunter", 79, "SF"),
    "sam-merrill": ("Sam Merrill", 77, "SG"),
    # 14 Detroit Pistons
    "cade-cunningham": ("Cade Cunningham", 92, "PG"),
    "ausar-thompson": ("Ausar Thompson", 82, "SF"),
    "jalen-duren": ("Jalen Duren", 82, "C"),
    "jaden-ivey": ("Jaden Ivey", 81, "SG"),
    "tobias-harris": ("Tobias Harris", 80, "PF"),
    # 15 Indiana Pacers
    "pascal-siakam": ("Pascal Siakam", 89, "PF"),
    "bennedict-mathurin": ("Bennedict Mathurin", 82, "SG"),
    "aaron-nesmith": ("Aaron Nesmith", 81, "SF"),
    "andrew-nembhard": ("Andrew Nembhard", 81, "PG"),
    "isaiah-jackson": ("Isaiah Jackson", 74, "C"),
    # 16 Toronto Raptors
    "scottie-barnes": ("Scottie Barnes", 85, "SF"),
    "brandon-ingram": ("Brandon Ingram", 84, "SF"),
    "rj-barrett": ("RJ Barrett", 82, "SG"),
    "immanuel-quickley": ("Immanuel Quickley", 81, "PG"),
    "jakob-poeltl": ("Jakob Poeltl", 80, "C"),
    # 17 Memphis Grizzlies
    "ja-morant": ("Ja Morant", 91, "PG"),
    "jaren-jackson-jr": ("Jaren Jackson Jr.", 89, "PF"),
    "santi-aldama": ("Santi Aldama", 81, "PF"),
    "jaylen-wells": ("Jaylen Wells", 79, "SF"),
    "kentavious-caldwell-pope": ("Kentavious Caldwell-Pope", 76, "SG"),
    # 18 Philadelphia 76ers
    "joel-embiid": ("Joel Embiid", 92, "C"),
    "tyrese-maxey": ("Tyrese Maxey", 86, "PG"),
    "paul-george": ("Paul George", 81, "SF"),
    "quentin-grimes": ("Quentin Grimes", 78, "SG"),
    "vj-edgecombe": ("VJ Edgecombe", 76, "SG"),
    # 19 Sacramento Kings
    "domantas-sabonis": ("Domantas Sabonis", 87, "C"),
    "demar-derozan": ("DeMar DeRozan", 85, "SF"),
    "zach-lavine": ("Zach LaVine", 85, "SG"),
    "keegan-murray": ("Keegan Murray", 79, "PF"),
    "dennis-schroder": ("Dennis Schroder", 77, "PG"),
    # 20 Boston Celtics
    "jaylen-brown": ("Jaylen Brown", 90, "SF"),
    "derrick-white": ("Derrick White", 87, "SG"),
    "payton-pritchard": ("Payton Pritchard", 82, "PG"),
    "neemias-queta": ("Neemias Queta", 79, "C"),
    "sam-hauser": ("Sam Hauser", 78, "SF"),
    # 21 New Orleans Pelicans
    "zion-williamson": ("Zion Williamson", 87, "PF"),
    "trey-murphy-iii": ("Trey Murphy III", 82, "SF"),
    "herbert-jones": ("Herbert Jones", 81, "SF"),
    "yves-missi": ("Yves Missi", 77, "C"),
    "jordan-poole": ("Jordan Poole", 76, "PG"),
    # 22 Phoenix Suns
    "devin-booker": ("Devin Booker", 91, "SG"),
    "jalen-green": ("Jalen Green", 83, "SG"),
    "dillon-brooks": ("Dillon Brooks", 82, "SF"),
    "mark-williams": ("Mark Williams", 80, "C"),
    "ryan-dunn": ("Ryan Dunn", 76, "SF"),
    # 23 Milwaukee Bucks
    "giannis-antetokounmpo": ("Giannis Antetokounmpo", 97, "PF"),
    "myles-turner": ("Myles Turner", 83, "C"),
    "kevin-porter-jr": ("Kevin Porter Jr.", 79, "PG"),
    "kyle-kuzma": ("Kyle Kuzma", 79, "SF"),
    "gary-trent-jr": ("Gary Trent Jr.", 76, "SG"),
    # 24 Miami Heat
    "bam-adebayo": ("Bam Adebayo", 88, "C"),
    "norman-powell": ("Norman Powell", 84, "SG"),
    "andrew-wiggins": ("Andrew Wiggins", 81, "SF"),
    "kelel-ware": ("Kel'el Ware", 80, "C"),
    "davion-mitchell": ("Davion Mitchell", 79, "PG"),
    # 25 Portland Trail Blazers
    "deni-avdija": ("Deni Avdija", 82, "SF"),
    "toumani-camara": ("Toumani Camara", 82, "PF"),
    "donovan-clingan": ("Donovan Clingan", 82, "C"),
    "jrue-holiday": ("Jrue Holiday", 81, "PG"),
    "shaedon-sharpe": ("Shaedon Sharpe", 81, "SG"),
    # 26 Chicago Bulls
    "coby-white": ("Coby White", 83, "SG"),
    "josh-giddey": ("Josh Giddey", 82, "PG"),
    "nikola-vucevic": ("Nikola Vucevic", 82, "C"),
    "matas-buzelis": ("Matas Buzelis", 81, "PF"),
    "kevin-huerter": ("Kevin Huerter", 77, "SG"),
    # 27 Charlotte Hornets
    "lamelo-ball": ("LaMelo Ball", 87, "PG"),
    "kon-knueppel": ("Kon Knueppel", 83, "SG"),
    "brandon-miller": ("Brandon Miller", 82, "SF"),
    "miles-bridges": ("Miles Bridges", 82, "PF"),
    "mason-plumlee": ("Mason Plumlee", 76, "C"),
    # 28 Washington Wizards
    "alexandre-sarr": ("Alexandre Sarr", 81, "C"),
    "cj-mccollum": ("CJ McCollum", 81, "SG"),
    "khris-middleton": ("Khris Middleton", 78, "SF"),
    "corey-kispert": ("Corey Kispert", 78, "SF"),
    "bub-carrington": ("Bub Carrington", 76, "PG"),
    # 29 Brooklyn Nets
    "michael-porter-jr": ("Michael Porter Jr.", 82, "SF"),
    "cam-thomas": ("Cam Thomas", 81, "SG"),
    "nicolas-claxton": ("Nicolas Claxton", 80, "C"),
    "ziaire-williams": ("Ziaire Williams", 76, "SF"),
    "egor-demin": ("Egor Demin", 72, "PG"),
    # 30 Utah Jazz
    "lauri-markkanen": ("Lauri Markkanen", 84, "PF"),
    "walker-kessler": ("Walker Kessler", 82, "C"),
    "keyonte-george": ("Keyonte George", 81, "PG"),
    "isaiah-collier": ("Isaiah Collier", 77, "PG"),
    "ace-bailey": ("Ace Bailey", 77, "SF"),
    # ---- Temporada 2026-27: jugadores nuevos / traspasos con roster nuevo ----
    "aj-dybantsa": ("AJ Dybantsa", 76, "SF"),
    "alex-sarr": ("Alex Sarr", 80, "C"),
    "ayo-dosunmu": ("Ayo Dosunmu", 79, "SG"),
    "brook-lopez": ("Brook Lopez", 81, "C"),
    "caleb-wilson": ("Caleb Wilson", 74, "PF"),
    "cameron-boozer": ("Cameron Boozer", 75, "PF"),
    "cason-wallace": ("Cason Wallace", 80, "SG"),
    "cedric-coward": ("Cedric Coward", 74, "SF"),
    "damian-lillard": ("Damian Lillard", 89, "PG"),
    "darius-acuff-jr": ("Darius Acuff Jr.", 73, "PG"),
    "darius-garland": ("Darius Garland", 86, "PG"),
    "darryn-peterson": ("Darryn Peterson", 74, "SG"),
    "dayron-sharpe": ("Dayron Sharpe", 76, "C"),
    "dejounte-murray": ("Dejounte Murray", 83, "PG"),
    "dereck-lively-ii": ("Dereck Lively II", 81, "C"),
    "derik-queen": ("Derik Queen", 76, "C"),
    "duncan-robinson": ("Duncan Robinson", 78, "SF"),
    "fred-vanvleet": ("Fred VanVleet", 82, "PG"),
    "herb-jones": ("Herb Jones", 81, "SF"),
    "jaime-jaquez-jr": ("Jaime Jaquez Jr.", 80, "SF"),
    "jayson-tatum": ("Jayson Tatum", 88, "SF"),
    "josh-hart": ("Josh Hart", 83, "SG"),
    "julian-champagnie": ("Julian Champagnie", 77, "SF"),
    "jusuf-nurkic": ("Jusuf Nurkic", 78, "C"),
    "kris-dunn": ("Kris Dunn", 78, "PG"),
    "kristaps-porzingis": ("Kristaps Porzingis", 85, "C"),
    "kyrie-irving": ("Kyrie Irving", 87, "PG"),
    "kyshawn-george": ("Kyshawn George", 77, "SF"),
    "max-christie": ("Max Christie", 78, "SG"),
    "max-strus": ("Max Strus", 79, "SG"),
    "mikel-brown-jr": ("Mikel Brown Jr.", 73, "PG"),
    "moussa-diabate": ("Moussa Diabate", 76, "PF"),
    "naz-reid": ("Naz Reid", 83, "C"),
    "nickeil-alexander-walker": ("Nickeil Alexander-Walker", 79, "SG"),
    "pj-washington": ("P.J. Washington", 82, "PF"),
    "ryan-rollins": ("Ryan Rollins", 78, "PG"),
    "sandro-mamukelashvili": ("Sandro Mamukelashvili", 76, "PF"),
    "tim-hardaway-jr": ("Tim Hardaway Jr.", 78, "SG"),
    "ty-jerome": ("Ty Jerome", 80, "PG"),
    "tyler-herro": ("Tyler Herro", 87, "SG"),
    "tyrese-haliburton": ("Tyrese Haliburton", 89, "PG"),
    "yaxel-lendeborg": ("Yaxel Lendeborg", 74, "PF"),
    "zach-edey": ("Zach Edey", 79, "C"),
    # ---- Banca: 3 suplentes por equipo (agregados para Fantasy) ----
    "andre-drummond": ("Andre Drummond", 78, "C"),
    "anfernee-simons": ("Anfernee Simons", 83, "SG"),
    "ajay-mitchell": ("Ajay Mitchell", 75, "PG"),
    "alex-caruso": ("Alex Caruso", 82, "SG"),
    "isaiah-joe": ("Isaiah Joe", 77, "SG"),
    "jordan-clarkson": ("Jordan Clarkson", 79, "PG"),
    "landry-shamet": ("Landry Shamet", 76, "SG"),
    "miles-mcbride": ("Miles McBride", 78, "PG"),
    "kelly-oubre-jr": ("Kelly Oubre Jr.", 80, "SF"),
    "obi-toppin": ("Obi Toppin", 79, "PF"),
    "tj-mcconnell": ("T.J. McConnell", 78, "PG"),
    "marvin-bagley-iii": ("Marvin Bagley III", 76, "PF"),
    "peyton-watson": ("Peyton Watson", 78, "SF"),
    "zeke-nnaji": ("Zeke Nnaji", 74, "PF"),
    "dylan-harper": ("Dylan Harper", 78, "PG"),
    "keldon-johnson": ("Keldon Johnson", 80, "SF"),
    "buddy-hield": ("Buddy Hield", 82, "SG"),
    "jaylon-tyson": ("Jaylon Tyson", 76, "SG"),
    "marcus-smart": ("Marcus Smart", 82, "PG"),
    "steven-adams": ("Steven Adams", 78, "C"),
    "tari-eason": ("Tari Eason", 80, "PF"),
    "collin-murray-boyles": ("Collin Murray-Boyles", 75, "PF"),
    "jakobe-walter": ("Jakobe Walter", 75, "SG"),
    "jamal-shead": ("Jamal Shead", 75, "PG"),
    "baylor-scheierman": ("Baylor Scheierman", 76, "SG"),
    "donte-divincenzo": ("Donte DiVincenzo", 81, "SG"),
    "jaylen-clark": ("Jaylen Clark", 75, "SG"),
    "terrence-shannon-jr": ("Terrence Shannon Jr.", 78, "SG"),
    "ron-holland": ("Ron Holland II", 77, "SF"),
    "bobby-portis": ("Bobby Portis", 82, "PF"),
    "nikola-jovic": ("Nikola Jovic", 78, "PF"),
    "simone-fontecchio": ("Simone Fontecchio", 77, "SF"),
    "kyle-filipowski": ("Kyle Filipowski", 78, "C"),
    "collin-sexton": ("Collin Sexton", 80, "PG"),
    "dalton-knecht": ("Dalton Knecht", 78, "SG"),
    "jarred-vanderbilt": ("Jarred Vanderbilt", 76, "PF"),
    "scoot-henderson": ("Scoot Henderson", 81, "PG"),
    "anthony-black": ("Anthony Black", 76, "PG"),
    "jonathan-isaac": ("Jonathan Isaac", 78, "PF"),
    "deanthony-melton": ("De'Anthony Melton", 78, "PG"),
    "moses-moody": ("Moses Moody", 78, "SG"),
    "khaman-maluach": ("Khaman Maluach", 76, "C"),
    "luke-kennard": ("Luke Kennard", 78, "SG"),
    "jeremiah-fears": ("Jeremiah Fears", 76, "PG"),
    "bilal-coulibaly": ("Bilal Coulibaly", 80, "SF"),
    "naji-marshall": ("Naji Marshall", 78, "SF"),
    "derrick-jones-jr": ("Derrick Jones Jr.", 79, "SF"),
    "gradey-dick": ("Gradey Dick", 78, "SG"),
    "grant-williams": ("Grant Williams", 78, "PF"),
    "royce-oneale": ("Royce O'Neale", 77, "SF"),
    "tidjane-salaun": ("Tidjane Salaun", 75, "PF"),
    "isaac-okoro": ("Isaac Okoro", 78, "SF"),
    "patrick-williams": ("Patrick Williams", 78, "PF"),
    "tre-jones": ("Tre Jones", 77, "PG"),
    "jerami-grant": ("Jerami Grant", 82, "PF"),
    "vince-williams-jr": ("Vince Williams Jr.", 77, "SF"),
    "malik-monk": ("Malik Monk", 81, "SG"),
    "nique-clifford": ("Nique Clifford", 74, "SG"),
    "precious-achiuwa": ("Precious Achiuwa", 77, "PF"),
    "ben-saraf": ("Ben Saraf", 74, "PG"),
    "noah-clowney": ("Noah Clowney", 75, "PF"),
    "nolan-traore": ("Nolan Traore", 74, "PG"),
    # ---- Banca 2: rosters completos, agregados para dar profundidad real a Fantasy ----
    "adem-bona": ("Adem Bona", 75, "C"),
    "caleb-love": ("Caleb Love", 75, "SG"),
    "cameron-payne": ("Cameron Payne", 78, "PG"),
    "dominick-barlow": ("Dominick Barlow", 74, "PF"),
    "justin-edwards": ("Justin Edwards", 75, "SF"),
    "labaron-philon": ("LaBaron Philon", 73, "PG"),
    "rayan-rupert": ("Rayan Rupert", 76, "SG"),
    "aaron-wiggins": ("Aaron Wiggins", 79, "SG"),
    "aday-mara": ("Aday Mara", 73, "C"),
    "brooks-barnhizer": ("Brooks Barnhizer", 73, "SG"),
    "nikola-topic": ("Nikola Topic", 77, "PG"),
    "otega-oweh": ("Otega Oweh", 73, "SG"),
    "thomas-sorber": ("Thomas Sorber", 76, "C"),
    "ariel-hukporti": ("Ariel Hukporti", 75, "C"),
    "dillon-jones": ("Dillon Jones", 74, "SF"),
    "mohamed-diawara": ("Mohamed Diawara", 73, "PF"),
    "pacome-dadiet": ("Pacome Dadiet", 74, "SF"),
    "tyler-kolek": ("Tyler Kolek", 75, "PG"),
    "ben-sheppard": ("Ben Sheppard", 77, "SG"),
    "jarace-walker": ("Jarace Walker", 78, "PF"),
    "jay-huff": ("Jay Huff", 74, "C"),
    "larry-nance": ("Larry Nance Jr.", 78, "PF"),
    "quenton-jackson": ("Quenton Jackson", 74, "SG"),
    "daron-holmes": ("Daron Holmes II", 75, "PF"),
    "jonas-valanciunas": ("Jonas Valanciunas", 81, "C"),
    "julian-strawther": ("Julian Strawther", 78, "SG"),
    "lonnie-walker": ("Lonnie Walker IV", 78, "SG"),
    "spencer-jones": ("Spencer Jones", 73, "SF"),
    "tyus-jones": ("Tyus Jones", 82, "PG"),
    "carter-bryant": ("Carter Bryant", 75, "SF"),
    "david-jones-garcia": ("David Jones Garcia", 73, "SF"),
    "jakobi-gillespie": ("Jakobi Gillespie", 72, "PG"),
    "luke-kornet": ("Luke Kornet", 78, "C"),
    "jock-landale": ("Jock Landale", 77, "C"),
    "marshun-newell": ("Marshun Newell", 72, "SG"),
    "vit-krejci": ("Vit Krejci", 76, "SG"),
    "craig-porter": ("Craig Porter Jr.", 74, "PG"),
    "ernest-udeh": ("Ernest Udeh Jr.", 72, "C"),
    "malik-thomas": ("Malik Thomas", 72, "SG"),
    "mario-hezonja": ("Mario Hezonja", 76, "SF"),
    "naeqwan-tomlin": ("Naeqwan Tomlin", 72, "PF"),
    "tyrese-proctor": ("Tyrese Proctor", 75, "PG"),
    "bogdan-bogdanovic": ("Bogdan Bogdanovic", 82, "SG"),
    "bruce-thornton": ("Bruce Thornton", 76, "PG"),
    "clint-capela": ("Clint Capela", 82, "C"),
    "jaesean-tate": ("Jae'Sean Tate", 77, "SF"),
    "quadir-copeland": ("Quadir Copeland", 72, "PG"),
    "reed-sheppard": ("Reed Sheppard", 80, "PG"),
    "alijah-martin": ("Alijah Martin", 73, "SG"),
    "allen-graves": ("Allen Graves", 72, "PF"),
    "jaden-bradley": ("Jaden Bradley", 72, "PG"),
    "jamison-battle": ("Jamison Battle", 74, "SF"),
    "nate-bittle": ("Nate Bittle", 73, "C"),
    "trayce-jackson-davis": ("Trayce Jackson-Davis", 78, "C"),
    "hugo-gonzalez": ("Hugo Gonzalez", 75, "SG"),
    "jordan-walsh": ("Jordan Walsh", 75, "SF"),
    "luka-garza": ("Luka Garza", 76, "C"),
    "bones-hyland": ("Bones Hyland", 78, "PG"),
    "isaiah-evans": ("Isaiah Evans", 73, "SG"),
    "joan-beringer": ("Joan Beringer", 74, "C"),
    "trey-lyles": ("Trey Lyles", 76, "PF"),
    "daniss-jenkins": ("Daniss Jenkins", 72, "PG"),
    "paul-reed": ("Paul Reed", 78, "PF"),
    "dru-smith": ("Dru Smith", 74, "PG"),
    "pelle-larsson": ("Pelle Larsson", 76, "SG"),
    "vladislav-goldin": ("Vladislav Goldin", 74, "C"),
    "brice-sensabaugh": ("Brice Sensabaugh", 76, "SF"),
    "cody-williams": ("Cody Williams", 76, "SF"),
    "jarvis-hayes": ("Jarvis Hayes", 74, "SF"),
    "john-konchar": ("John Konchar", 76, "SG"),
    "josh-okogie": ("Josh Okogie", 77, "SG"),
    "jake-laravia": ("Jake LaRavia", 77, "SF"),
    "kevon-looney": ("Kevon Looney", 78, "C"),
    "matisse-thybulle": ("Matisse Thybulle", 78, "SF"),
    "robbie-avila": ("Robbie Avila", 72, "C"),
    "jeremy-sochan": ("Jeremy Sochan", 80, "PF"),
    "robert-williams": ("Robert Williams III", 78, "C"),
    "yang-hansen": ("Yang Hansen", 76, "C"),
    "colin-castleton": ("Colin Castleton", 73, "C"),
    "goga-bitadze": ("Goga Bitadze", 78, "C"),
    "jase-richardson": ("Jase Richardson", 76, "SG"),
    "jevon-carter": ("Jevon Carter", 77, "PG"),
    "tristan-da-silva": ("Tristan da Silva", 77, "SF"),
    "gary-payton-ii": ("Gary Payton II", 78, "SG"),
    "gui-santos": ("Gui Santos", 74, "SF"),
    "jonathan-kuminga": ("Jonathan Kuminga", 83, "PF"),
    "will-richard": ("Will Richard", 74, "SG"),
    "collin-gillespie": ("Collin Gillespie", 76, "PG"),
    "koa-peat": ("Koa Peat", 75, "PF"),
    "koby-brea": ("Koby Brea", 74, "SG"),
    "oso-ighodaro": ("Oso Ighodaro", 76, "C"),
    "hunter-dickinson": ("Hunter Dickinson", 76, "C"),
    "jordan-hawkins": ("Jordan Hawkins", 79, "SG"),
    "karlo-matkovic": ("Karlo Matkovic", 74, "PF"),
    "micah-peavy": ("Micah Peavy", 74, "SF"),
    "saddiq-bey": ("Saddiq Bey", 78, "SF"),
    "jamir-watkins": ("Jamir Watkins", 72, "SF"),
    "julian-reese": ("Julian Reese", 73, "PF"),
    "tre-johnson": ("Tre Johnson", 79, "SG"),
    "tristan-vukcevic": ("Tristan Vukcevic", 75, "C"),
    "will-riley": ("Will Riley", 76, "SF"),
    "caleb-martin": ("Caleb Martin", 80, "SF"),
    "marcus-sasser": ("Marcus Sasser", 76, "PG"),
    "cam-christie": ("Cam Christie", 73, "SG"),
    "jordan-miller": ("Jordan Miller", 75, "SF"),
    "yanic-niederhauser": ("Yanic Niederhauser", 73, "C"),
    "pat-connaughton": ("Pat Connaughton", 77, "SG"),
    "ryan-kalkbrenner": ("Ryan Kalkbrenner", 74, "C"),
    "sion-james": ("Sion James", 74, "SG"),
    "tre-mann": ("Tre Mann", 78, "PG"),
    "leonard-miller": ("Leonard Miller", 74, "PF"),
    "mac-mcclung": ("Mac McClung", 74, "PG"),
    "noa-essengue": ("Noa Essengue", 75, "PF"),
    "zach-collins": ("Zach Collins", 79, "C"),
    "kris-murray": ("Kris Murray", 75, "SF"),
    "taylor-hendricks": ("Taylor Hendricks", 78, "PF"),
    "walter-clayton": ("Walter Clayton Jr.", 76, "PG"),
    "alex-karaban": ("Alex Karaban", 74, "SF"),
    "bj-edwards": ("BJ Edwards", 72, "SG"),
    "daeqwon-plowden": ("Daeqwon Plowden", 72, "PF"),
    "maxime-raynaud": ("Maxime Raynaud", 75, "C"),
    "danny-wolf": ("Danny Wolf", 75, "C"),
    "drake-powell": ("Drake Powell", 74, "SF"),
    "josh-minott": ("Josh Minott", 75, "PF"),
    "markel-brown": ("Markel Brown", 72, "SG"),
    "moritz-wagner": ("Moritz Wagner", 78, "PF"),
    "terance-mann": ("Terance Mann", 78, "SG"),
    "trevon-scott": ("Trevon Scott", 72, "PF"),
    "aj-green": ("AJ Green", 77, "SG"),
    "caris-levert": ("Caris LeVert", 81, "SG"),
    "jericho-sims": ("Jericho Sims", 75, "C"),
    "kasparas-jakucionis": ("Kasparas Jakucionis", 76, "PG"),
    "pete-nance": ("Pete Nance", 73, "PF"),
}

# suplentes agregados solo para llenar banca en Fantasy (no aparecen en sobres normales ni cuentan para completar equipo)
BENCH_SLUGS = {
    "andre-drummond", "anfernee-simons", "ajay-mitchell", "alex-caruso", "isaiah-joe",
    "jordan-clarkson", "landry-shamet", "miles-mcbride", "kelly-oubre-jr", "obi-toppin",
    "tj-mcconnell", "marvin-bagley-iii", "peyton-watson", "zeke-nnaji", "dylan-harper",
    "keldon-johnson", "buddy-hield", "jaylon-tyson", "marcus-smart", "steven-adams",
    "tari-eason", "collin-murray-boyles", "jakobe-walter", "jamal-shead", "baylor-scheierman",
    "donte-divincenzo", "jaylen-clark", "terrence-shannon-jr", "ron-holland", "bobby-portis",
    "nikola-jovic", "simone-fontecchio", "kyle-filipowski", "collin-sexton", "dalton-knecht",
    "jarred-vanderbilt", "scoot-henderson", "anthony-black", "jonathan-isaac", "deanthony-melton",
    "moses-moody", "khaman-maluach", "luke-kennard", "jeremiah-fears", "bilal-coulibaly",
    "naji-marshall", "derrick-jones-jr", "gradey-dick", "grant-williams", "royce-oneale",
    "tidjane-salaun", "isaac-okoro", "patrick-williams", "tre-jones", "jerami-grant",
    "vince-williams-jr", "malik-monk", "nique-clifford", "precious-achiuwa", "ben-saraf",
    "noah-clowney", "nolan-traore",
    "adem-bona", "caleb-love", "cameron-payne", "dominick-barlow", "justin-edwards",
    "labaron-philon", "rayan-rupert", "aaron-wiggins", "aday-mara", "brooks-barnhizer",
    "nikola-topic", "otega-oweh", "thomas-sorber", "ariel-hukporti", "dillon-jones",
    "mohamed-diawara", "pacome-dadiet", "tyler-kolek", "ben-sheppard", "jarace-walker",
    "jay-huff", "larry-nance", "quenton-jackson", "daron-holmes", "jonas-valanciunas",
    "julian-strawther", "lonnie-walker", "spencer-jones", "tyus-jones", "carter-bryant",
    "david-jones-garcia", "jakobi-gillespie", "luke-kornet", "jock-landale", "marshun-newell",
    "vit-krejci", "craig-porter", "ernest-udeh", "malik-thomas", "mario-hezonja",
    "naeqwan-tomlin", "tyrese-proctor", "bogdan-bogdanovic", "bruce-thornton", "clint-capela",
    "jaesean-tate", "quadir-copeland", "reed-sheppard", "alijah-martin", "allen-graves",
    "jaden-bradley", "jamison-battle", "nate-bittle", "trayce-jackson-davis", "hugo-gonzalez",
    "jordan-walsh", "luka-garza", "bones-hyland", "isaiah-evans", "joan-beringer",
    "trey-lyles", "daniss-jenkins", "paul-reed", "dru-smith", "pelle-larsson",
    "vladislav-goldin", "brice-sensabaugh", "cody-williams", "jarvis-hayes", "john-konchar",
    "josh-okogie", "jake-laravia", "kevon-looney", "matisse-thybulle", "robbie-avila",
    "jeremy-sochan", "robert-williams", "yang-hansen", "colin-castleton", "goga-bitadze",
    "jase-richardson", "jevon-carter", "tristan-da-silva", "gary-payton-ii", "gui-santos",
    "jonathan-kuminga", "will-richard", "collin-gillespie", "koa-peat", "koby-brea",
    "oso-ighodaro", "hunter-dickinson", "jordan-hawkins", "karlo-matkovic", "micah-peavy",
    "saddiq-bey", "jamir-watkins", "julian-reese", "tre-johnson", "tristan-vukcevic",
    "will-riley", "caleb-martin", "marcus-sasser", "cam-christie", "jordan-miller",
    "yanic-niederhauser", "pat-connaughton", "ryan-kalkbrenner", "sion-james", "tre-mann",
    "leonard-miller", "mac-mcclung", "noa-essengue", "zach-collins", "kris-murray",
    "taylor-hendricks", "walter-clayton", "alex-karaban", "bj-edwards", "daeqwon-plowden",
    "maxime-raynaud", "danny-wolf", "drake-powell", "josh-minott", "markel-brown",
    "moritz-wagner", "terance-mann", "trevon-scott", "aj-green", "caris-levert",
    "jericho-sims", "kasparas-jakucionis", "pete-nance",
}

def equipo_bonito(folder):
    # "01-Oklahoma-City-Thunder" -> "Oklahoma City Thunder"
    return folder.split("-", 1)[1].replace("-", " ")

players = []
missing_files = []
for slug, (name, ovr, pos) in DATA.items():
    pass

# recorrer carpetas para garantizar match 1:1 con las fotos
seen = set()
for team_folder in sorted(os.listdir(FOTOS)):
    tdir = os.path.join(FOTOS, team_folder)
    if not os.path.isdir(tdir):
        continue
    for fn in sorted(os.listdir(tdir)):
        if not fn.lower().endswith(".jpg"):
            continue
        slug = os.path.splitext(fn)[0]
        seen.add(slug)
        if slug not in DATA:
            missing_files.append(f"{team_folder}/{slug}")
            continue
        name, ovr, pos = DATA[slug]
        players.append({
            "nombre": name,
            "slug": slug,
            "equipo": equipo_bonito(team_folder),
            "equipo_carpeta": team_folder,
            "media": ovr,
            "posicion": pos,
            "foto": f"fotos-nba/{team_folder}/{fn}",
            "banca": slug in BENCH_SLUGS,
        })

# jugadores en DATA sin foto
no_photo = [s for s in DATA if s not in seen]

players.sort(key=lambda p: (-p["media"], p["nombre"]))

with open(os.path.join(BASE, "medias.json"), "w", encoding="utf-8") as f:
    json.dump(players, f, ensure_ascii=False, indent=2)

with open(os.path.join(BASE, "medias.csv"), "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["nombre", "equipo", "media", "posicion", "foto"])
    for p in players:
        w.writerow([p["nombre"], p["equipo"], p["media"], p["posicion"], p["foto"]])

print(f"Jugadores escritos: {len(players)}")
print(f"Fotos sin media en DATA: {missing_files}")
print(f"Medias en DATA sin foto: {no_photo}")
print("\nTop 5:")
for p in players[:5]:
    print(f"  {p['media']} {p['nombre']} ({p['equipo']})")
print("Bottom 5:")
for p in players[-5:]:
    print(f"  {p['media']} {p['nombre']} ({p['equipo']})")
